'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), os = require('node:os');
const { defineProvider, registerProvider, createMockHost, checkSchema } = require('../lib');
const { SkillFileStore } = require('../lib/skill-files');
const source = fs.readFileSync(path.resolve(__dirname, '../../dsh-door/lib/bridge/protocol.js'), 'utf8').replace(/\r\n/g, '\n').replace("import path from 'node:path';", "'use strict';\nconst path = require('node:path');").replace(/export /g, '');
assert.equal(fs.readFileSync(path.join(__dirname, '../lib/schema.js'), 'utf8').replace(/\r\n/g, '\n').split('\nmodule.exports')[0].trim(), source.trim(), 'SDK schema rules must match the wire protocol');
const fixture = { id: 'fixture', name: 'Fixture', version: '1.0.0', capabilities: [{ id: 'fixture.echo', title: 'Echo', kind: 'resource', riskTier: 'read', effects: [], inputSchema: { type: 'object', properties: { text: { type: 'string', maxLength: 4 } }, required: ['text'], additionalProperties: false }, outputSchema: { type: 'object', properties: { text: { type: 'string' } }, required: ['text'], additionalProperties: false } }], invoke: (_, input) => input };
(async () => {
  const host = createMockHost(), dispose = registerProvider({ ideBridge: host }, fixture);
  assert.equal(host.catalog().capabilities.length, 1);
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'dsh-sdk-'));
  const context = { cwd, clientId: 'one', workspaceTrusted: true, userInitiated: true, approved: true, signal: new AbortController().signal };
  assert.deepEqual(await host.invoke('fixture.echo', { text: 'echo' }, context), { text: 'echo' });
  await assert.rejects(host.invoke('fixture.echo', { text: 'too long' }, context), error => error.code === -32046);
  await assert.rejects(host.invoke('fixture.echo', { text: 'ok', extra: true }, context), error => error.code === -32046);
  assert.throws(() => registerProvider({ ideBridge: host }, fixture), error => error.code === -32046);
  assert.throws(() => checkSchema({ pattern: 'invalid' }, undefined, true), error => error.code === -32046);
  const invalid = defineProvider({ ...fixture, invoke: () => ({ text: 1 }) });
  await assert.rejects(invalid.invoke('fixture.echo', { text: 'ok' }, context), error => error.code === -32046);
  const write = { ...fixture, id: 'write', capabilities: [{ ...fixture.capabilities[0], id: 'write.file', riskTier: 'workspace-write', effects: ['workspace.write'] }] };
  host.registerProvider(write); await assert.rejects(host.invoke('write.file', { text: 'ok' }, { ...context, approved: false }), error => error.code === -32044);
  await assert.rejects(host.invoke('write.file', { text: 'ok' }, { ...context, workspaceTrusted: false }), error => error.code === -32044);
  const cancelled = new AbortController(); cancelled.abort(); await assert.rejects(host.invoke('fixture.echo', { text: 'ok' }, { ...context, signal: cancelled.signal }), error => error.code === -32800);
  dispose(); assert.equal(host.catalog().capabilities.length, 1);
  const store = new SkillFileStore({ roots: ctx => ({ project: path.join(ctx.cwd, '.dsh/skills'), user: path.join(cwd, 'user/skills') }) });
  const body = name => `---\nname: ${name}\ndescription: Example skill\n---\n\nInstructions.\n`;
  let plan = store.preview({ action: 'create', name: 'example', scope: 'project', content: body('example') }, context);
  assert(!fs.existsSync(plan.file), 'Preview must not write files');
  assert.throws(() => store.commit(plan.planId, { ...context, approved: false }), /确认/);
  assert.throws(() => store.commit(plan.planId, { ...context, clientId: 'other' }), /不属于/);
  store.commit(plan.planId, context); assert.equal(fs.readFileSync(plan.file, 'utf8'), body('example'));
  assert.throws(() => store.preview({ action: 'create', name: 'example', scope: 'project', content: body('example') }, context), /已存在/);
  plan = store.preview({ action: 'update', file: plan.file, content: body('example') + 'Updated.\n' }, context);
  const file = plan.file, before = plan.before;
  fs.writeFileSync(file, before + 'External edit.\n'); assert.throws(() => store.commit(plan.planId, context), /已经变化/); assert(fs.readFileSync(file, 'utf8').includes('External edit'));
  plan = store.preview({ action: 'update', file, content: body('example') + 'Updated.\n' }, context); store.commit(plan.planId, context);
  assert(store.trash(context).some(item => item.action === 'update'));
  plan = store.preview({ action: 'enabled', file, enabled: false }, context); store.commit(plan.planId, context); assert(fs.readFileSync(file, 'utf8').includes('disable-model-invocation: true'));
  plan = store.preview({ action: 'enabled', file, enabled: true }, context); store.commit(plan.planId, context); assert(fs.readFileSync(file, 'utf8').includes('disable-model-invocation: false'));
  plan = store.preview({ action: 'delete', file }, context); const deleted = store.commit(plan.planId, context); assert(!fs.existsSync(file));
  plan = store.preview({ action: 'restore', trashId: deleted.recoveryId }, context);
  fs.writeFileSync(file, 'New occupant'); assert.throws(() => store.commit(plan.planId, context), /已经变化/); assert.equal(fs.readFileSync(file, 'utf8'), 'New occupant'); fs.unlinkSync(file);
  store.commit(plan.planId, context); assert(fs.readFileSync(file, 'utf8').includes('Updated.'));
  assert.throws(() => store.preview({ action: 'update', file, content: body('renamed') }, context), /不能更改名称/);
  assert.throws(() => store.preview({ action: 'delete', file: path.join(cwd, 'outside/SKILL.md') }, context), /只读/);
  assert.throws(() => store.preview({ action: 'delete', file }, { ...context, workspaceTrusted: false }), /受信任/);
  assert.throws(() => store.preview({ action: 'delete', file }, { ...context, clientId: undefined }), /客户端身份/);
  assert.throws(() => store.preview({ action: 'create', name: '../escape', scope: 'project', content: body('escape') }, context), /名称无效/);
  assert.throws(() => store.preview({ action: 'create', name: 'nul', scope: 'project', content: body('nul') }, context), /名称无效/);
  assert.throws(() => store.preview({ action: 'update', file, content: body('example') + '界'.repeat(50000) }, context), /超过限制/);
  const link = path.join(cwd, '.dsh/skills/linked'); fs.symlinkSync(path.dirname(file), link, 'junction');
  assert.throws(() => store.preview({ action: 'delete', file: path.join(link, 'SKILL.md') }, context), /链接/); fs.unlinkSync(link);
  const recovery = store.trash(context).find(item => item.action === 'delete');
  plan = store.preview({ action: 'delete', file }, context); store.commit(plan.planId, context);
  const restore = store.preview({ action: 'restore', trashId: recovery.id }, context); fs.writeFileSync(recovery.trashFile, 'tampered'); assert.throws(() => store.commit(restore.planId, context), /恢复来源/);
  let now = 0; const expiring = new SkillFileStore({ roots: () => ({ project: path.join(cwd, '.dsh/skills') }), now: () => now });
  plan = expiring.preview({ action: 'create', name: 'expired', scope: 'project', content: body('expired') }, context); now = 600001; assert.throws(() => expiring.commit(plan.planId, context), /过期/);
  fs.rmSync(cwd, { recursive: true, force: true });
  console.log('SDK schema parity, registration, output validation, trust, cancellation, skill preview/write/recovery, stale sources and link boundaries passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
